import Providers from "./providers";
import theme from "./theme";

export const metadata = {
  title: "emaun hyde",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers theme={theme}>{children}</Providers>
      </body>
    </html>
  );
}
